### ISSUE TITLE
Fails to render Hero content when navigating through client 

### ISSUE THREAD

**Issue by aksharahegde** [aksharahegde/pahachaan#3]
**Issue**
Fails to render Hero content when navigating through client and below message will be displayed:
You should use slots with <ContentQuery>!

**Screenshot**
![image](https://github.com/aksharahegde/pahachaan/assets/22255990/9a745b2a-79af-47ea-80b6-5c373e54c611)

**Steps to reproduce**
1. Load the homepage
2. Go to any other page
3. Click on home icon again

**Comment by fayazara** [comment]
https://github.com/aksharahegde/pahachaan/assets/15716057/46f72afa-3029-4af2-b19c-9da368a11efa

I was about to log this issue 😂
